name-template: '$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: minor
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '⚙️ Enhancements'
    labels:
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🔧 Maintenance'
    labels:
      - 'dependencies'
      - 'maintenance'
  - title: '📜 Documentation'
    labels:
      - 'documentation'
template: |
  ## Changes

  $CHANGES

  Contributors to this release: $CONTRIBUTORS

  **Full changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
