---
title: "DFD Hugo Zen theme"
baseURL: "https://example.org/"
defaultContentLanguage: "en"
disableKinds: [taxonomy, terms]
enableGitInfo: true
enableRobotsTXT: true
ignoreErrors: ["error-disable-taxonomy"]
languageCode: "en-CA" # non-multilingual only
paginate: 10
paginatePath: "page"
removePathAccents: true
rssLimit: 20

taxonomies:
  tag: tags
  series: series

frontmatter:
  lastmod: [":git", "lastmod", ":fileModTime", "date", "publishDate"]

permalinks:
  "/": "/:sections/:slug"

markup:
  goldmark:
    parser:
      attribute:
        block: true
    renderer:
      unsafe: false
  highlight:
    codeFences: true
    noClasses: false
  tableOfContents:
    endLevel: 5
    ordered: true
    startLevel: 2

outputFormats:
  SearchIndex:
    baseName: "searchindex"
    isPlainText: true
    mediaType: "application/json"
    notAlternative: true
  nredirects:
    baseName: _redirects
    isPlainText: true
    mediaType: "text/nredirects"
  nheaders:
    baseName: _headers
    isPlainText: true
    mediaType: "text/nheaders"

mediaTypes:
  "text/nheaders":
    suffixes: ""
  "text/nredirects":
    suffixes: ""

outputs:
  home: ["HTML", "RSS", "JSON", "SearchIndex", "nredirects", "nheaders"]
  section: ["HTML", "RSS", "JSON"]
  taxonomy: ["HTML", "RSS", "JSON"]
  term: ["HTML", "RSS", "JSON"]

params:
  author:
    name: "Your Name"
    url: "https://example.org/somepage"
    avatar: "path/to/some-image.jpg"
  breadcrumbSections:
    - about
    - documentation
  contact: "info@example.org"
  copyright: |
    Copyright [Daniel F. Dickinson](https://www.danielfdickinson.ca/),
    [Fredrik Jonsson](https://xdeb.net/)
    (original Hugo Zen theme author),
    and contributors. Licensed under the [GNU Public License v2 or
    later](http://www.gnu.org/licenses/old-licenses/gpl-2.0.html).
  description: "Example site for DFD's fork of the Zen theme for Hugo."
  dateformat: "2 January, 2006"
  favicon: "apple-touch-icon.png"
  feedlinks: true
  icon: "apple-touch-icon.png"
  image: "apple-touch-icon.png"
  # imageMaxWidth: 400
  logoHeight: 32
  logoWidth: 32
  mainSections:
    - documentation
    - post
  mobilemenu: true
  noImageConvert: false
  noSrcSetDefault: false
  pageCanonical: false
  poweredby: true
  realfavicongenerator: true
  redirectsDomains:
    - "http://dfd-hugo-zen-theme.netlify.app https://dfd-hugo-theme-zen.wildtechgarden.ca 301!"
    - "https://dfd-hugo-zen-theme.netlify.app https://dfd-hugo-theme-zen.wildtechgarden.ca 301!"
    - "http://dfd-hugo-theme-zen.wildtechgarden.ca https://dfd-hugo-theme-zen.demo.wildtechgarden.com 301!"
    - "https://dfd-hugo-theme-zen.wildtechgarden.ca https://dfd-hugo-theme-zen.demo.wildtechgarden.com 301!"
    - "http://dfd-hugo-theme-zen.demo.wildtechgarden.com https://dfd-hugo-theme-zen.demo.wildtechgarden.com 301!"
  relatedposts: true
  sassTranspiler: libsass
  searchAllPages: true
  sidebar: true
  submitted: true
  tables: true
  # themeColor: #aaa
  # useBaseURL: false

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true

module:
  replacements: "gitlab.com/danielfdickinson/dfd-hugo-theme-zen -> ../.."
  imports:
    - path: gitlab.com/danielfdickinson/dfd-hugo-theme-zen
      mounts:
        - source: archetypes
          target: archetypes
        - source: assets
          target: assets
        - source: i18n
          target: i18n
        - source: layouts
          target: layouts
        - source: static
          target: static
  mounts:
    - source: assets
      target: assets
    - source: i18n
      target: i18n
    - source: layouts
      target: layouts
    - source: static
      target: static
...
