---
title: "DFD Hugo Zen theme"
baseURL: "https://example.org/"
languageCode: "en-CA"
defaultContentLanguage: "en"
pluralizelisttitles: false
removePathAccents: true
paginate: 10
paginatePath: "page"
rssLimit: 20
outputFormats:
  SearchIndex:
    mediaType: "application/json"
    baseName: "searchindex"
    isPlainText: true
    notAlternative: true

outputs:
  home: ["HTML", "RSS", "JSON", "SearchIndex"]
  section: ["HTML", "RSS", "JSON"]

params:
  contact: "info@example.org"
  description: "Example site for DFD's fork of the zen theme for Hugo."
  dateformat: "2 January, 2006"
  favicon: "apple-touch-icon.png"
  feedlinks: true
  icon: "apple-touch-icon.png"
  image: "apple-touch-icon.png"
  imageMaxWidth: 400
  logoWidth: 64
  mobileMenu: true
  poweredby: true
  realfavicongenerator: true
  sidebar: true
  submitted: true
  author:
    name: "Your Name"
    url: "https://example.org/somepage"
    avatar: "path/to/some-image.jpg"

module:
  replacements: "gitlab.com/danielfdickinson/dfd-hugo-theme-zen -> ../.."
  imports:
    - path: gitlab.com/danielfdickinson/dfd-hugo-theme-zen
